spring:
  datasource:
    url: jdbc:mysql://localhost:3307/book_list
    username: root
    password: example
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:com/raisetech/mapper/*.xml

